# Generated by Django 3.2.5 on 2021-07-18 07:40

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2021, 7, 18, 13, 25, 31, 407751))),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 13, 25, 31, 411747)),
        ),
    ]
