# Generated by Django 3.2.5 on 2021-07-18 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210718_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 13, 25, 55, 897735)),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 13, 25, 55, 899736)),
        ),
    ]
