# Generated by Django 3.2.5 on 2021-07-22 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_postmodel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 12, 55, 5, 409424)),
        ),
    ]
