# Generated by Django 3.2.5 on 2021-07-22 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_postmodel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 12, 56, 23, 834635)),
        ),
    ]
