# Generated by Django 3.2.5 on 2021-07-22 10:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_image'),
        ('post', '0009_alter_postmodel_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 22, 16, 28, 32, 149231)),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usermodel')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.postmodel')),
            ],
        ),
    ]
