# Generated by Django 3.2.6 on 2021-08-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='otp',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
